#!/usr/bin/env python3

import os
import subprocess

def run_installer():
    try:
        import rnmd
    except Exception as exception:
        print("Could not locate rnmd which is required to run this script.")
        print("Do you want to install it? (y/n)")
        answer = input()
        if(answer != "y"):
            exit()

        pip_installed = subprocess.check_output(['python3', '-m','pip','--V'])
        if("No module" in pip_installed):
            print("Could not install 'rnmd' pip3 is not installed on your system, please install and try again!")
            exit()

        os.system("pip3 install rnmd")



run_installer()

import rnmd.rnmd as rnmd
import sys

markdown_doc_path = "/home/pmarkus/repos/rnmd/notebook/echo.md"
backup_path = "None"
run_command = "rnmd"
update_backup = False

script_name = __file__
script_arg_index = sys.argv.index(script_name)
passed_args = sys.argv[script_arg_index + 1:]

rnmd.run_proxy(markdown_doc_path, backup_path, passed_args, command = run_command, update_backup = update_backup)
    